const calculators=[
{id:'dpp',name:'DPP & PPN 12%',icon:'receipt',page:'pages/pajak/dpp.html'},
{id:'basic',name:'Kalkulator Biasa',icon:'calculator',page:'pages/umum/kalkulator.html'},
{id:'hebel',name:'Kalkulator Hebel',icon:'blocks',page:'pages/bangunan/hebel.html'},
{id:'keramik',name:'Kalkulator Keramik',icon:'grid-2x2',page:'pages/bangunan/keramik.html'},
{id:'hpp',name:'Kalkulator HPP',icon:'wallet',page:'pages/bisnis/hpp.html'},
{id:'harga-jual',name:'Kalkulator Harga Jual',icon:'tag',page:'pages/bisnis/harga-jual.html'},
{id:'margin',name:'Kalkulator Margin',icon:'percent',page:'pages/bisnis/margin.html'},
{id:'markup',name:'Kalkulator Markup',icon:'trending-up',page:'pages/bisnis/markup.html'},
{id:'diskon',name:'Kalkulator Diskon',icon:'badge-percent',page:'pages/bisnis/diskon.html'},
{id:'profit',name:'Kalkulator Profit',icon:'coins',page:'pages/bisnis/profit.html'},
{id:'bep',name:'Kalkulator BEP',icon:'scale',page:'pages/bisnis/bep.html'},
{id:'target-penjualan',name:'Target Penjualan',icon:'target',page:'pages/bisnis/target-penjualan.html'},
{id:'pajak',name:'Pajak / PPN',icon:'landmark',page:'pages/pajak/pajak.html'},
{id:'persentase',name:'Persentase',icon:'percent',page:'pages/umum/persentase.html'},
{id:'volume',name:'Volume',icon:'box',page:'pages/umum/volume.html'},
{id:'luas',name:'Luas',icon:'square',page:'pages/umum/luas.html'},
{id:'berat',name:'Konversi Berat',icon:'weight',page:'pages/umum/berat.html'},
{id:'konversi',name:'Konversi Satuan',icon:'ruler',page:'pages/umum/konversi.html'},
{id:'cat',name:'Kebutuhan Cat',icon:'paintbrush',page:'pages/bangunan/cat.html'},
{id:'beton',name:'Volume Beton',icon:'construction',page:'pages/bangunan/beton.html'},
{id:'pipa',name:'Kebutuhan Pipa',icon:'cable',page:'pages/bangunan/pipa.html'},
{id:'besi-beton',name:'Besi Beton',icon:'grip',page:'pages/bangunan/besi-beton.html'},
{id:'plafon',name:'Kebutuhan Plafon',icon:'layers',page:'pages/bangunan/plafon.html'},
{id:'atap',name:'Kebutuhan Atap',icon:'home',page:'pages/bangunan/atap.html'},
{id:'rab',name:'RAB Sederhana',icon:'clipboard-list',page:'pages/proyek/rab.html'}
];